name: ph2t
channels:
    - conda-forge
    - pypi
dependencies:
    - python=3.5.2
    - ipython=5.0.0
    - matplotlib=1.5.1
    - notebook=4.2.2
    - numpy=1.11.1
    - pandas=0.18.1
    - requests=2.10.0
    - scikit-learn=0.17.1
    - scipy=0.18.0
    - seaborn
    - statsmodels
    - toolz
